config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  root 'pages#home'
  resources :articles
  get '/pages/about',to:'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login',to: 'sessions#new'
  post 'login' ,to: 'sessions#create'
  delete 'logout',to:'sessions#destroy'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
end    

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/concerns/article.rb
class Article <  ApplicationRecord
    validates :title , presence: true, length:{minimum:3,maximum:50}
    validates :description , presence: true, length:{minimum:10,maximum:300}
end    

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :comments
    has_many :articles
    validates :username, presence: true, uniqueness: { case_sensitive: false },
               length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
               uniqueness: { case_sensitive: false },
               format: { with: VALID_EMAIL_REGEX } 
    has_secure_password                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:notice] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article , only: [:edit,:update,:destroy,:show]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def index
        @article=Article.all
    end    
    def new
        @article=Article.new
    end

    def create
        @article=Article.new(article_params)
        @article.user=current_user
        if @article.save
            flash[:notice]="Article Sucessfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end        
    end

    def edit
       
    end 

    

    def destroy
        set_article
        @article.destroy
        if(@article.destroy)
            flash[:notice]='Article sucessfully destroyed'
        end    
        redirect_to articles_path
    
    end    

    
    def update
       
        if @article.update(article_params)
            flash[:notice]="Article Sucessfully update"
            redirect_to article_path(@article)
        else
            render 'edit'
        end        
    end  
    def show
       # @article=Article.find(params[:id]) 
       
     end    

    private
     def set_article
        @article=Article.find(params[:id])
     end   
     def article_params
        params.require(:article).permit(:title,:description,:user_id)
     end 
     
          

     def require_same_user
        if current_user != @article.user
            flash[:notice] = "You can only edit or delete your own articles"
            redirect_to root_path
        end 
    end        
end    

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:description, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?

    end
    def about
    
    end  
      
end    

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    def create
        user=User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice]="Logged In Successfully"
            redirect_to user_path(user)
        else
            flash.now[:notice]="LogIn failed"
            render 'new'
        end    
    end
    def destroy
        session[:user_id] = nil
        flash[:notice] = "You have logged out"
        redirect_to root_path
    end            
end    

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
    def require_same_user

      if current_user != @user
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
      end
      
    end
      
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<ul>    
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg  %></li>
    <% end %>
</ul>
<% end %>       

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>

            <div class="form-group">

                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :title,class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div> 
            </div>       
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>    
                <div class="col-sm-8">
                    <%= f.text_area :description,class: "form-control" , placeholder: "Description of article" %>
                </div>    
            </div>   

            <div class="form-group">

            <div class="col-sm-offset-2 col-sm-10">
            
            <%= f.submit class: 'btn btn-primary btn-lg' %>
            
            </div>
            
            </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">

            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

        </div>
    </div>
</div>        

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<h2 align="center">
    <%= link_to "create new article" ,new_article_path %>
</h2>
<table align="center" border='1'>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th >Created By</th>
        <th colspan="3"></th>
       
    </tr>
    <% @article.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= article.user.username if article.user%></td>
        

        <td><%= link_to "Edit",edit_article_path(article) %></td>
        <td><%= link_to "Show",article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>
</table>            

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center description"><strong>Description:<strong></h4>
    <hr>
     <%= simple_format(@article.description) %>
    <div class="article-action">
     <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>     

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            @Created by:Megha Sonkusare
        </small>
    <footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <ul align="center" class='decul'>
      <li><%= msg %></li>
    </ul>
  <% end %>  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    
    <%= link_to 'Alpha-blog',root_path,class:"navbar-brand",id:"logo"%>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
      <% if logged_in? %>
        <%= link_to 'Article ',articles_path %>
      <% end %>  
      </li>

      <li class="nav-item">
        <%= link_to 'Log In',login_path %>
      </li>
      <li class="nav-item">
        
        <%= link_to 'Log Out',logout_path , method: :delete%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2 " type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation'  %>
  <%=render 'layouts/messages' %>
    
  <div class="container">
    <%= yield %>
  </div> 
  <%= render 'layouts/footer' %>  
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>ALPHA BLOG</h1>
    <%= link_to "Sign up now", "signup",class:"btn btn-primary btn-lg" %>
</div>    

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<ul>    
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg  %></li>
    <% end %>
</ul>
<% end %>       

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

            <div class="form-group">

                <div class="control-label col-sm-2">
                    <%= f.label :Username %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :username,class: "form-control", placeholder: "Username", autofocus: true %>
                </div> 
            </div>       
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :email %>
                </div>    
                <div class="col-sm-8">
                    <%= f.text_field :email,class: "form-control" , placeholder: "Email id" %>
                </div>    
            </div>  
            <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :password %>
            </div>    
            <div class="col-sm-8">
                <%= f.text_field :password,class: "form-control" , placeholder: "Password" %>
            </div>    
        </div>   


            <div class="form-group">

            <div class="col-sm-offset-2 col-sm-10">
            
            <%= f.submit class: 'btn btn-primary btn-lg' %>
            
            </div>
            
            </div>
        <% end %>
    </div>
</div>       

app/views/users/edit.html.erb
<h1 align="center">Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Users</h1>

<table align="center" border="1">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3" text-align='center'>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
    <% end %>
    <tr><td colspan='5'><%= link_to 'New User', new_user_path %></td></tr>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1 align="center" color="blue">New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<p class="field">
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p class="field"><strong>Email:</strong>
  <%= @user.email %>
</p>
<p class="field">
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</p>